@startuml

hide person

storage Drivers {
    storage Adapters {
        storage UseCases {
            storage Entities {
                label " "
            }

            interface Manager
        }
    }
    entity "Database\nManager" as dbManager
    database Database

    dbManager -right-|> Manager
    Manager -> Entities
    dbManager -down-> Database
}

@enduml