@startuml
!include ../../metamodels/architecture.iuml
left to right direction

subdomain "Complaint Subdomain" {

    service "Complaint Microservice" as complaint {
        functionality "Complaint Management"
    }
    database "Complaint Database" as db

    interact(complaint, db, left)

}

@enduml