@startuml
!include ../../metamodels/architecture.iuml
left to right direction

subdomain "User Subdomain" {

    service "Authentication Microservice" as authn {
        functionality "Account Management"
        functionality "SmartCard Management"
    }

    database "Authentication Database" as db

    interact(authn, db, left)
}

@enduml