@startmindmap
!include ../metamodels/mindmaps.iuml

goal("Optimize Waste Collection")

actor("Dumpsters")
    impact("Track amount of waste")
        deliverable("Volume sensors")
    impact("Notify if broken")
        deliverable("Sensors and actuators for opening")
    impact("Track citizens' accesses")
        deliverable("Smart card reader")

actor("Trucks")
    impact("Track their real-time position")
        deliverable("Geolocalization")
    impact("Ad-hoc routes\n(call by need)")
        deliverable("Routing system")
    impact("Notify issues")
        deliverable("Mobile application")

actor("Citizens")
    impact("Open dumpsters with smart card")
        deliverable("Smart cards")
    impact("Extraordinary waste\nat-home collection")
        deliverable("Extraordinary waste\nbooking application")
    impact("Notify complaints")
        deliverable("Mobile application")

legend left
    Level 1 = Goal
    Level 2 = Actors
    Level 3 = Impacts
    Level 4 = Deliverables
endlegend
@endmindmap