@startuml
!include ../../metamodels/context-maps.iuml

subdomain(Disposal, disposal_subdomain) {
    context_supplier("Dumpster's Monitoring\n& Control", dumpster, left)
    context("Collection Point\nManagement", collection_point)
    context_supplier("Disposal Point", disposal_point, right)
}

subdomain(Collection, collection_subdomain) {
    context("Mission", mission)
    context_supplier("Truck's Monitoring\n & Control", truck, right)
    context("Booking", booking)
}

subdomain(User, user_subdomain) {
    context("Smart Card", smartcard)
    context_supplier("Authentication\n", authn, right)
}

subdomain(Complaint, complaint_subdomain) {
    context_supplier("Complaint", complaint)
}

generic_downstream(smartcard, dumpster, up)
generic_downstream(mission, dumpster, up)
generic_downstream(mission, truck, down)
partnership(mission, booking, left)
generic_downstream(mission, disposal_point)
generic_downstream(booking, authn, right)
generic_downstream(complaint, authn, up)
generic_downstream(collection_point, dumpster, down)
generic_downstream(dumpster, complaint)

@enduml