@startuml
!include ../metamodels/use-cases.iuml
actor "Truck" as tr
actor Citizen as c

scenarios "Common Waste" {
    ' Citizens
    usecase "Dispose Of the Garbage" as dispose
    usecase "Open the Dumpster with the Smart Card" as smartcard
    usecase "Update Garbage Weight" as update
    usecase "Dumpster Full" as full

    include(dispose, smartcard, up)
    include(dispose, update, down)

    uses(c, dispose, right)
    uses(c, smartcard, right)

    extend(full, update, left)


    ' Truck Riders
    usecase "Start a Mission" as mission
    usecase "Stop at a Collection Point" as collection
    usecase "Empty a Dumpster" as empty

    include(collection, empty, up)
    include(mission, collection, up)

    ' uses(tr, mission)
    uses(tr, collection, left)
    uses(tr, empty)

    include(mission, full, left)
}


@enduml