@startuml
!include ../metamodels/use-cases.iuml
actor "Truck" as tr
actor Citizen as c

scenarios "Extraordinary Waste" {
    ' Citizens
    usecase "Book an Extraordinary Waste Collection" as booking

    uses(c, booking, right)

    ' Truck Riders
    usecase "Go at Citizen's House" as go
    usecase "PickUp Extraordinary Waste" as pickup
    usecase "Come Back at the Disposal Point" as disposal
    include(go, pickup, down)
    include(pickup, disposal, down)
    include(go, booking, left)

    uses(tr, go, right)
    uses(tr, pickup, right)
    uses(tr, disposal, right)
}

@enduml
