@startwbs
!include ../metamodels/requirement-breakdown.iuml

goal(Optimize Waste Collection)

'Dumpster Infrastructure
requirement(Dumpster infrastructure)

function(Open dumpsters\nwith smart-cards)
feature(Authenticate citizen)
feature(Open and close\ndumpsters)

function(Collect and share data)
feature(Update occupied volume)
feature(Store information about\ncitizens' disposals)
feature(Send "full-dumpster" notification)
feature(Raise complaints)

'Citizen App
requirement(Citizen app)
function(Check dumpsters'\nstatus)
feature(Display dumpsters\non graphic interface)
feature(Check dumpsters'\navailability)
feature(Check dumpster's\noccupied volume)

function(Book extraordinary\nwaste disposal)
feature(Create a request)
feature(Check requests' status)

function(Raise complaints)
feature(Write a complaint)
feature(Send complaint)

'Mission Management
requirement(Mission Management)
function(Plan ordinary waste\ndisposal missions)
feature(Look for other dumpsters to\ncollect near the full one)
feature(Calculate best route)

function(Plan extraordinary waste\ndisposal missions)
feature(Observe extraordinary \nmission requests)
feature(Calculate best route)

'Admin Dashboard
requirement(Admin dashboard)
function(Display collection\npoints' status)
feature(Display dumpsters'\navailability)
feature(Display dumpsters'\noccupied volume)
feature(Display dumpsters' type)
feature(Display collected type of waste)

function(Display trucks'\nreal time status)
feature(Display trucks'\nposition)
feature(Display trucks'\ncarried waste)

function(Display missions)
feature(Display active missions)

function(Display complaints)
feature(Display list of complaints)
feature(Check complaint's details)

function(Register new citizens)
feature(Create smart-cards\nfor new citizens)

legend left
    Blue = Goal
    Green = Requirements
    Yellow = Functions
    Grey = Features
endlegend
@endwbs