name: Generate GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  update-gh-pages:
    name: Generate GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Embed plantuml in markdown
        uses: alessandro-marcantoni/puml-markdown@v0.1.1
      - name: Generate markdown documentation
        uses: ldeluigi/markdown-docs@v0
        with:
          src: .
          dst: ./gh-pages
          icon: truck-check
      - name: Deploy GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
