name: Generate GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  update-gh-pages:
    name: Generate GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: tokusumi/markdown-embed-code@main
          with:
            markdown: "*.md"
            token: ${{ secrets.GITHUB_TOKEN }}
            message: "Synchronizing markdowns"
            silent: true
      - name: Run action
        uses: ldeluigi/markdown-docs@v0
        with:
          src: .
          dst: ./gh-pages
      - name: Deploy GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages