name: Generate GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  update-gh-pages:
    name: Generate GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setting up node
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Current dir
        run: pwd
      - name: Init node
        run: npm init -y
      - name: Add plantuml for markdown
        run: npm i -g puml-for-markdown
      - name: Embed plantuml in markdown
        run: puml-for-markdown
      - name: Generate markdown documentation
        uses: ldeluigi/markdown-docs@v0
        with:
          src: .
          dst: ./gh-pages
      - name: Deploy GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
