name: Push Plantuml Diagrams to project-management Repository

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      
      - run: echo ${{ github.actor }}

      - name: Commit & Push diagrams
        if: github.actor == 'SimoneRomagnoli'
        uses: SimoneRomagnoli/copy-files-action@v1.0.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.SR_API_TOKEN_GITHUB }}
        with:
          pattern: "*.pm.puml"
          dst_repo: "SmartWasteCollection/project-management"
          dst_dir: "uml"
          dst_branch: "main"
          commit_msg: "docs(uml): update uml diagrams"
          user_name: "SimoneRomagnoli"
          user_email: "simone.romagnoli10@studio.unibo.it"

