name: Push Plantuml Diagrams to presentation Repository

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  push-plantuml-diagrams:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Commit & Push diagrams
        if: github.actor == 'SimoneRomagnoli'
        uses: SimoneRomagnoli/copy-files-action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.SR_API_TOKEN_GITHUB }}
        with:
          pattern: "*.puml"
          dst_repo: "SmartWasteCollection/presentation"
          dst_dir: "uml"
          dst_branch: "main"
          commit_msg: "docs(uml): update uml diagrams"
          user_name: "SimoneRomagnoli"
          user_email: "simone.romagnoli10@studio.unibo.it"

      - name: Commit & Push metamodels
        if: github.actor == 'SimoneRomagnoli'
        uses: SimoneRomagnoli/copy-files-action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.SR_API_TOKEN_GITHUB }}
        with:
          pattern: "*.iuml"
          dst_repo: "SmartWasteCollection/presentation"
          dst_dir: "metamodels"
          dst_branch: "main"
          commit_msg: "docs(uml): update uml diagrams"
          user_name: "SimoneRomagnoli"
          user_email: "simone.romagnoli10@studio.unibo.it"
